# Generated by Django 3.0.6 on 2020-07-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='id',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='calculation_coffee',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='calculation_exercise',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='calculation_water',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='image',
            field=models.ImageField(default='pp.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='join.User'),
        ),
    ]
