# Generated by Django 3.0.6 on 2020-07-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
