# Generated by Django 3.0.6 on 2020-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0006_auto_20200719_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='calculation_coffee',
            field=models.TextField(default='00-00-0000 : 0'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='calculation_exercise',
            field=models.TextField(default='00-00-0000 : no 00.0'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='calculation_history',
            field=models.TextField(default='00-00-0020 : 000 cal, 0 food'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='calculation_water',
            field=models.TextField(default='00-00-0000 : 0'),
        ),
    ]
