# Generated by Django 3.0.6 on 2020-07-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0008_auto_20200719_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='image',
            field=models.ImageField(default='pp.jpg', upload_to='static/media/images'),
        ),
    ]
